json.code voucher.code
json.content voucher.content
json.discount voucher.discount
json.effective_at voucher.effective_at
json.expiration_at voucher.expiration_at
json.max_amount voucher.max_amount
json.title voucher.title
json.threshold voucher.threshold
json.condition_str voucher.render_condition
json.point voucher.point
